language: node_js
node_js:
- "iojs-v1.6.4"
env:
  global:
  - COVERALLS_SERVICE_NAME="travis-ci"
  - COVERALLS_REPO_TOKEN="2vmMsfQIGRDVJLmpTOmgPicnnG2rHqZy3"
before_install:
- npm install -g bower
script: npm run travis
notifications:
  slack:
    secure: f23z5nlDa6Feh8wtuD9DnVUHys06R6NJBM7P0i2B2unho0aLHkJ+rzRJ2FM+7yDEW5FfKI4kNCFd58ZB4lAqZ86h9hvTkPjAAq4wUJWAUlxok+WI5ldhvntzGIRv9BSb2eKqgrUtHYptjMSaBOjXEXgA8YXDPYATnZT4nd8oGY8=
